[package]
name = "rumqttpub"
version = "0.1.0"
authors = ["ubuntu"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#rumqttc = {path = "/home/ubuntu/RND/rust/rumqttnew/rumqttc"}
rumqttc = "0.1.2"
clap ="*"
