name: testlib-ci 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    #runs-on: self-hosted
    defaults:
      run:
        working-directory: ./testlib
    steps:
    - uses: actions/checkout@v2
    - name: Format
      run: cargo fmt
    - name: Lint Checking
      run: cargo clippy  
    - name: Run tests
      run: cargo test --verbose
    - name: Build
      run: cargo build --release
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
          name: libtestlib.rlib 
          path: testlib/target/release/libtestlib.rlib 
