name: RustMqttc 

on: 
 push:
         branches:
                 -main     
jobs:
    build:
       runs-on: ubuntu-latest
       steps:
            - uses: actions/checkout@v1
            - uses: PRADEEPKJ/mqttc@main
              with:
                args: cd rumqttpub  && cargo fmt -- --check && cargo clippy -- -Dwarnings && cargo test
                args: cd rumqttsub  && cargo fmt -- --check && cargo clippy -- -Dwarnings && cargo test
