name: RustMqttc 

on: 
 push:
         branches:
                 -main     
jobs:
    build:
       runs-on: ubuntu-latest
       steps:
            - uses: actions/checkout@v1
            - uses: icepuma/rust-action@main
              with:
                args: cd integration-test && cargo fmt -- --check && cargo clippy -- -Dwarnings && cargo test
