name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cd rumqttsub && cargo build --verbose
    - name: 'Create a file'
      run: echo ${{ matrix.node-version }} > my_file.txt
    - name: 'Accidently upload to the same artifact via multiple jobs'
      uses: 'actions/upload-artifact@v2'
      with:
              name: my-artifact
              path: ${{ github.workspace }}
     
    
