name: RustmqttSchedbased

on:
  schedule:
  - cron: '*/3 * * * *'
    
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cd rumqttpub && cargo run --release --verbose   
